---
server:
  scheme: http
  prefix: customers
  name: customer-service
  mode: release
  host: 0.0.0.0
  port: 1102
discovery:
  interval: "3s"
  timeout: "2s"
  deregister: "10s"
database:
  host: db
  dbname: postgres
  user: postgres
  password: postgres # pragma: allowlist secret
  port: '5432'
  sslmode: disable
logging:
  level: warn
